"""add unit_price column to order product association table

Revision ID: 946cf6f83d4a
Revises: 432b2cfe96a4
Create Date: 2024-07-31 01:24:54.647827

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '946cf6f83d4a'
down_revision: Union[str, None] = '432b2cfe96a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_product_association',
                  sa.Column('unit_price', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_product_association', 'unit_price')
    # ### end Alembic commands ###
